### ISSUE TITLE
issue custom notification after version 0.38

### ISSUE THREAD

**Issue by jrspowers** [Blueforcer/awtrix-light#13]
hello is on version 0.38 get these strange characters at my temperature sensor of my room on the screen after restarting the screen this does not help yet why is this?

```yaml
service: mqtt.publish
    data:
      topic: AwtrixLight/notify
      payload: >-
        {   "text":
        "{{trigger.to_state.state}}{{trigger.to_state.attributes.unit_of_measurement}}",  
        "icon": "52352",   "rainbow": true,   "duration": 30 }
```
