### ISSUE TITLE
[BUG?] Clock shuts down when matrix is turned off for 2h

### ISSUE THREAD

**Issue by TheGroundZero** [Blueforcer/awtrix-light#224]
# Bug report

## Describe the bug

I'm not entirely certain whether this is a bug or expected behaviour.

I have an automation that turns off the display (and the transitions) at night.
I noticed in the morning, the device would be off and I'd need to manually turn it on again by holding the 2 buttons.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.70

## To Reproduce

Here's the automation:

```yaml
automation:
  - id: awtrix_night
    alias: Awtrix turn off at night
    description: Turn the display of the Awtrix off at night
    trigger:
      - type: illuminance
        platform: device
        device_id: 7cb35d836fcd914d47337990435ba877
        entity_id: 1b9cec4097d58a857a0dbcca27e86cc8
        domain: sensor
        above: 20
        for:
          seconds: 30
        id: "on"
      - type: illuminance
        platform: device
        device_id: 7cb35d836fcd914d47337990435ba877
        entity_id: 1b9cec4097d58a857a0dbcca27e86cc8
        domain: sensor
        below: 20
        for:
          seconds: 30
        id: "off"
    condition: []
    action:
      - choose:
          - conditions:
              - alias: Turn on
                condition: trigger
                id: "on"
            sequence:
              - alias: Awtrix Matrix on
                type: turn_on
                device_id: 7cb35d836fcd914d47337990435ba877
                entity_id: light.awtrix_dd2824_matrix
                domain: light
              - alias: Transition on
                type: turn_on
                device_id: 7cb35d836fcd914d47337990435ba877
                entity_id: switch.awtrix_dd2824_transition
                domain: switch
          - conditions:
              - alias: Turn off
                condition: trigger
                id: "off"
            sequence:
              - alias: Awtrix Matrix off
                type: turn_off
                device_id: 7cb35d836fcd914d47337990435ba877
                entity_id: light.awtrix_dd2824_matrix
                domain: light
              - alias: Transition off
                type: turn_off
                device_id: 7cb35d836fcd914d47337990435ba877
                entity_id: switch.awtrix_dd2824_transition
                domain: switch
    mode: single
```

## Expected behavior

The device's screen turns off at night and on during the day.

## Screenshots

![image](https://github.com/Blueforcer/awtrix-light/assets/2406013/5f616e41-9a02-42a5-9479-69a3f2dcb1b2)

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```
