### ISSUE TITLE
[QUESTION] Lost custom app after Restart ESP

### ISSUE THREAD

**Issue by 120318** [Blueforcer/awtrix-light#46]
# Question
![image](https://user-images.githubusercontent.com/20685540/230636191-e5feec09-aa12-4ef6-a0bd-45259fb0bc0b.png)
If I click the Restart ESP button, my custom app will lost. is it normal?

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.47

**Comment by Blueforcer** [comment]
Custom "apps" are only temporary hold in RAM. Just send it again

**Comment by 120318** [comment]
> Custom "apps" are only temporary hold in RAM. Just send it again

Is it possible and are there plans to make them permanently stored？

**Comment by schneekluth** [comment]
> > Custom "apps" are only temporary hold in RAM. Just send it again
> 
> Is it possible and are there plans to make them permanently stored？

Just use MQTT's retained messages feature for your custom apps. Your broker will store your custom apps and resends them when you restart your pixel clock. See https://github.com/Blueforcer/awtrix-light/issues/11

Example:
```yaml
- service: mqtt.publish
  data:
    qos: 2
    retain: true
    payload: >-
      {
        "text": "{{ states.sensor.exchange_rate_1_btc.state | round(0) }}",
        "icon": "bitcoin"
      }
    topic: pixelclock/custom/bitcoin
```
