### ISSUE TITLE
[BUG] Memory leak which overtime results in slow or no network response and unit becomes unresponsive

### ISSUE THREAD

**Issue by Bazz-Man** [Blueforcer/awtrix-light#485]
# Bug report

Free memory slow drops resulting in a non responsive unit on the network although the time is still shown but with odd pixels flashing randomly.  Occassionally will auto reset and work until memory leaks away once again.

![image](https://github.com/Blueforcer/awtrix-light/assets/33786321/5defac8d-c1b5-475b-9171-ad91db0763da)

## Describe the bug

Monitoring the Free Ram via Home assistant it slowly reduces as per graph which occurs when sending messages to the indicator elements via HA's light on command in an automation. However if messages are sent via MQTT service in HA then no memory leak is seen even though it results in the same functional result (i,e, the indicator turns on).  The time taken for memory to leak away to impact the clock is directly related to the amount of messages sent.  i.e. if you send a message once per 30 seconds it will take around 15 hours to leak away but if you send it once every 3 seconds then it takes a few hours.  If the unit is reset/rebooted normal function is restored until the memory leaks away once more.  Whilst I appreciate this is not necessarily normal usage to send the same command at frequent intervals, I stumbled across it whilst doing some monitoring for another device and wanted a confirmed message being display via changing colours on the indicator but found the clock stopped responding after a few days, then through further testing found root cause.  I believe this could affect users over a number of days or even weeks with odd behavoiur and freezing only resolved through a restart.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - Also tested on a stand alone ESP32 TTGO OLED board to prove it was code and not hardware
  - Tested on AWTRIX-LIGHT versions 0.87 to 0.94 (current)

## To Reproduce

Send via HA automation a turn on light command for the indicator

```
alias: XTEST - Awtrix memory test
description: ""
trigger:
  - platform: time_pattern
    seconds: /3
    enabled: true
condition: []
action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.awtrix_f07204_indicator_2
mode: single
```
This is sending an **ON** payload via MQTT to **awtrix_test/3c71bff07204/f07204_ind2/cmd_t**  topic

## Expected behavior

No memory loss should be seen.  If the following command is sent via MQTT service which performs the same function of turning on the indicator, no memory loss is recorded and the unit continues to run with no issues.

```
alias: XTEST - Awtrix memory test2
description: ""
trigger:
  - platform: time_pattern
    seconds: /3
    enabled: true
condition: []
action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: awtrix_test/indicator2
      payload: "{\"color\":[255,0,0]}"
mode: single
```
This is sending a JSON **{"color":[255,0,0]}** payload via MQTT to **awtrix_test/indicator2**  topic

## Screenshots

Memory graph showing leak with messages being sent every 3 seconds via HA turn on light command
![image](https://github.com/Blueforcer/awtrix-light/assets/33786321/2cf9c492-2bec-412b-a050-f4bd0089fdc4)

## Logs
None

## Additional context
None
