### ISSUE TITLE
[FEATURE REQUEST] Persistent TextOffset between scrolling text and icon

### ISSUE THREAD

**Issue by schneekluth** [Blueforcer/awtrix-light#92]
# Feature Request

### Is your feature request related to a problem?
No

### Describe the solution / feature you'd like
It would be great to maintain the given `TextOffset` from the chosen Icon. Currently the defined offset only applies to the start of a new message. If the space between Icon and scrolling text could be persistent it would look much nicer when using a progressbar.

![23-04-28 14-48-51 2307](https://user-images.githubusercontent.com/5740913/235152946-d5591a5f-1308-4e7b-9987-d879497b9ba2.jpg)

**Comment by Blueforcer** [comment]
please post your json

**Comment by schneekluth** [comment]
Works perfect with 0.59. TestOffset was indeed used wrong. Thank you.

![spotify](https://user-images.githubusercontent.com/5740913/235298356-a0016cd5-d040-4207-a7b9-ad937eff2868.gif)

**Comment by zkrystian** [comment]
> Works perfect with 0.59. TestOffset was indeed used wrong. Thank you.
> 
> ![spotify](https://user-images.githubusercontent.com/5740913/235298356-a0016cd5-d040-4207-a7b9-ad937eff2868.gif)

Can you post json for this? Progress bar looks nice

**Comment by jrspowers** [comment]
> Works perfect with 0.59. TestOffset was indeed used wrong. Thank you.
> 
> 
> 
> ![spotify](https://user-images.githubusercontent.com/5740913/235298356-a0016cd5-d040-4207-a7b9-ad937eff2868.gif)
> 
> 

hello very nice and how did you do this with that bar underneath it is very nice that the playback time shows that? I'm curious 😊

**Comment by schneekluth** [comment]
Of course! The [Spotify Integration](https://www.home-assistant.io/integrations/spotify/) in Homeassistant provides a media_player with 2 attributes that allow to calculate progress of played song:

```yaml
- service: mqtt.publish
  data:
    qos: 2
    retain: false
    payload: >-
      {
        "text": "{{ state_attr('media_player.spotify', 'media_artist') }} - {{ state_attr('media_player.spotify', 'media_title') }}",
        "icon": "spotify",
        "rainbow": false,
        "duration": 10,
        "pushIcon": 0,
        "textCase": 2,
        "progress": {{ ( states.media_player.spotify.attributes.media_position / states.media_player.spotify.attributes.media_duration * 100 ) | round() }},
        "progressC": "18B04C"
      }
    topic: pixelclock/notify
```

**Comment by jrspowers** [comment]
> ```yaml
> service: mqtt.publish
>   data:
>     qos: 2
>     retain: false
>     payload: >-
>       {
>         "text": "{{ state_attr('media_player.spotify', 'media_artist') }} - {{ state_attr('media_player.spotify', 'media_title') }}",
>         "icon": "spotify",
>         "rainbow": false,
>         "duration": 10,
>         "pushIcon": 0,
>         "textCase": 2,
>         "progress": {{ ( states.media_player.spotify.attributes.media_position / states.media_player.spotify.attributes.media_duration * 100 ) | round() }},
>         "progressC": "18B04C"
>       }
>     topic: pixelclock/notify
> ```

hello how is your very automation ? could you share this too?

**Comment by schneekluth** [comment]
```yaml
- alias: notify_pixelclock_spotify
  trigger:
    - platform: state
      entity_id: media_player.spotify
  condition:
    not:
      - condition: state
        entity_id: media_player.spotify
        state: "idle"
  action:
    - service: mqtt.publish
      data:
        qos: 2
        retain: false
        payload: >-
          {
            "text": "{{ state_attr('media_player.spotify', 'media_artist') }} - {{ state_attr('media_player.spotify', 'media_title') }}",
            "icon": "spotify",
            "rainbow": false,
            "duration": 10,
            "pushIcon": 0,
            "textCase": 2,
            "progress": {{ ( states.media_player.spotify.attributes.media_position / states.media_player.spotify.attributes.media_duration * 100 ) | round() }},
            "progressC": "18B04C"
          }
        topic: pixelclock/notify
```
